export const NEXT_BUILD_STEP = "NEXT_BUILD_STEP";
export const UPDATE_LAYOUT_STEP_VIEW = "UPDATE_LAYOUT_STEP_VIEW";
export const REORDER_COMPONENT_STACK = "REORDER_COMPONENT_STACK";
export const ADD_COMPONENT_TO_STACK = "ADD_COMPONENT_TO_STACK";
