export const NEXT_BUILD_STEP = "NEXT_BUILD_STEP";
export const SHOW_COMPONENT_TYPES_STEP = "SHOW_COMPONENT_TYPES_STEP";
export const REORDER_COMPONENT_STACK = "REORDER_COMPONENT_STACK";
export const ADD_COMPONENT_TO_STACK = "ADD_COMPONENT_TO_STACK";
export const DELETE_COMPONENT_FROM_STACK = "DELETE_COMPONENT_FROM_STACK";
export const UPDATE_LAYOUT_STYLE = "UPDATE_LAYOUT_STYLE";
export const UPDATE_PHOTOGALLERY_STYLE = "UPDATE_PHOTOGALLERY_STYLE";
export const LAYOUT_TYPE_SELECTED = "LAYOUT_TYPE_SELECTED";
export const LAYOUT_STYLE_PRESET_SELECTED = "LAYOUT_STYLE_PRESET_SELECTED";
export const COMPONENT_STYLE_PRESET_SELECTED =
  "COMPONENT_STYLE_PRESET_SELECTED";
