export const NEXT_BUILD_STEP = "NEXT_BUILD_STEP";
export const SHOW_COMPONENT_TYPES_STEP = "SHOW_COMPONENT_TYPES_STEP";
export const REORDER_COMPONENT_STACK = "REORDER_COMPONENT_STACK";
export const ADD_COMPONENT_TO_STACK = "ADD_COMPONENT_TO_STACK";
export const DELETE_COMPONENT_FROM_STACK = "DELETE_COMPONENT_FROM_STACK";
export const UPDATE_LAYOUT_STYLE = "UPDATE_LAYOUT_STYLE";
export const UPDATE_MENU_STYLE = "UPDATE_MENU_STYLE";
export const UPDATE_PHOTO_GALLERY_STYLE = "UPDATE_PHOTO_GALLERY_STYLE";
export const UPDATE_VIDEO_GALLERY_STYLE = "UPDATE_VIDEO_GALLERY_STYLE";
export const UPDATE_COMPONENT_CUSTOM_CLASS = "UPDATE_COMPONENT_CUSTOM_CLASS";
export const LAYOUT_TYPE_SELECTED = "LAYOUT_TYPE_SELECTED";
export const LAYOUT_STYLE_PRESET_SELECTED = "LAYOUT_STYLE_PRESET_SELECTED";
export const MENU_STYLE_PRESET_SELECTED = "MENU_STYLE_PRESET_SELECTED";
export const COMPONENT_STYLE_PRESET_SELECTED =
  "COMPONENT_STYLE_PRESET_SELECTED";
export const STYLE_EDITOR_SHOW_NEXT_COMPONENT =
  "STYLE_EDITOR_SHOW_NEXT_COMPONENT";
export const STYLE_EDITOR_SHOW_PREV_COMPONENT =
  "STYLE_EDITOR_SHOW_PREV_COMPONENT";
export const STYLE_EDITOR_SHOW_COMPONENT = "STYLE_EDITOR_SHOW_COMPONENT";
export const TOGGLE_MENU = "TOGGLE_MENU";
